# Mini Dataset Minimal Improvement
# Add depth features and keep fuser

_base_: "convfuser.yaml"

model:
  fuser:
    type: ConvFuser
    in_channels: [80, 256]
    out_channels: 256
  
  encoders:
    camera:
      vtransform:
        add_depth_features: true
